#!/bin/bash

echo "Logging in to ECR"
aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION

echo "Fetching Docker image"
docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:rhobot